apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: goserver
  labels:
    app: goserver
spec:
  selector:
    matchLabels:
      app: goserver
  replicas: 2
  template:
    metadata:
      name: "goserver"
      labels: 
        app: "goserver"
    spec:
      containers:
        - name: goserver
          image: "xhachimanx/hello-go:v2"